FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Define environment variables for the three URLs
ENV HOST_BIKES="http://127.0.0.1:3031/bikes"
ENV HOST_FOOD="http://127.0.0.1:3032/food"
ENV HOST_TOYS="http://127.0.0.1:3033/toys"
ENV PORT=3021

# Expose the port your Express.js application will run on (change as needed)
EXPOSE 3021

# Start your Express.js application
CMD ["node", "src/server.js"]